name: Wiki Update Demo
run-name: Pushing Updates to BTA Wiki
on:
    push:
      branches:
        - wiki
jobs:
    post-to-wiki:
        name: Post Updates to Wiki
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}
                path: bta
            - name: Check out automation code
              uses: actions/checkout@v4
              with:
                repository: 'amidatelion/bta-wiki-automation'
                path: wiki-gen
            - name: Check state of directories again
              run: |
                  pwd
                  ls -la bta
                  ls -la wiki-gen
            - name: Enable Cloudflare API workaround
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/toggleCloudflareApi.py enable
            - name: Run Faction automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/factionRenderer.py
            - name: Run Factory automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/factoryRenderer.py
            - name: Run Pilot automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/pilotRenderer.py
            - name: Run vehicle automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/vehicleRenderer.py
            - name: Disable Cloudflare API workaround
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/toggleCloudflareApi.py disable